# Generated by Django 6.0.2 on 2026-03-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('horario', models.CharField(max_length=255)),
                ('mapa_embed', models.TextField(blank=True, help_text='Código iframe o URL de mapa (opcional).')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Información de contacto',
                'verbose_name_plural': 'Información de contacto',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('mensaje', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('platos', 'Platos'), ('ambiente', 'Ambiente'), ('equipo', 'Equipo'), ('ingredientes', 'Ingredientes'), ('bebidas', 'Bebidas')], default='platos', max_length=20)),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Imágenes de galería',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
