# Generated by Django 5.2.6 on 2026-03-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado (Cocina)'), ('preparando', 'En Preparación'), ('listo', 'Listo para Entrega'), ('entregado', 'Entregado'), ('cuenta', 'Cuenta Solicitada'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
    ]
