# Generated by Django 6.0.2 on 2026-02-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(choices=[('ceviche', 'Ceviches'), ('caliente', 'Platos Calientes'), ('bebida', 'Bebidas'), ('postre', 'Postres')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_envio', models.CharField(choices=[('cocina', 'Cocina'), ('barra', 'Barra')], max_length=20)),
            ],
        ),
    ]
