# Generated by Django 5.2.6 on 2026-03-01 23:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_codigo', models.ImageField(blank=True, null=True, upload_to='qr_mesas/')),
            ],
        ),
    ]
