# Generated by Django 6.0.2 on 2026-02-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('qr_codigo', models.ImageField(blank=True, null=True, upload_to='qr_mesas/')),
            ],
        ),
    ]
